from utils.CVUtils import RESOLUTION_ENUM
from utils.CVUtils import (
    RESOLUTION_ENUM as RESOLUTION,
    HAARCASCADE_ENUM as HAARCASCADES,
    FRAMERATE_ENUM as FPS,
)


class SettingsManager:
    RECODRING_IMAGE_SIZE: RESOLUTION_ENUM = RESOLUTION.LOW
    PROCESSING_IMAGE_SIZE: RESOLUTION = RESOLUTION.LOWEST
    HAARCASCADE_FACE_EXTRACTOR: HAARCASCADES = HAARCASCADES.FRONTALFACE_DEFAULT
    PREVIEW_FRAMERATE: FPS = FPS.LOW
    PROCESSING_FRAMERATE: FPS = FPS.LOW
    PPG_TARGET_CLARITY_THRESHOLD: float = 6
    MIN_HEARTRATE_BPM: float = 40
    MAX_HEARTRATE_BPM: float = 240
    PPG_BANDPASS_ORDER: int = 3
    RECORDING_TIME_SECONDS: float = 60 / MIN_HEARTRATE_BPM * 2
